# Generated by Django 5.1.3 on 2024-12-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_kabacan_app', '0002_remove_spot_spot_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spot Category',
                'verbose_name_plural': 'Spot Categories',
                'db_table': 'spot_category_tbl',
            },
        ),
    ]
