# Generated by Django 5.1.3 on 2024-12-03 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_kabacan_app', '0003_spotcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='explore_kabacan_app.spotcategory'),
        ),
    ]
