# Generated by Django 5.1.3 on 2024-12-04 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_kabacan_app', '0004_spot_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Select what tourist spot you are assigned to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='explore_kabacan_app.spot'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the user can login to the system'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Whether the user can access the super admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Whether the user has the admin permission to system'),
        ),
    ]
