# Generated by Django 5.1.3 on 2024-12-07 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore_kabacan_app', '0005_customuser_assigned_to_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='email',
        ),
    ]
