# Generated by Django 5.1.3 on 2024-12-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_kabacan_app', '0006_remove_tourist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='visitor_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Group', 'Group')], max_length=255, null=True),
        ),
    ]
