# Generated by Django 5.1.3 on 2024-12-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_kabacan_app', '0007_tourist_visitor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='number_of_students',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
