# Generated by Django 5.1.3 on 2024-12-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_kabacan_app', '0008_tourist_number_of_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='number_of_students',
        ),
        migrations.AddField(
            model_name='tourist',
            name='number_of_visitors',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
