# Generated by Django 5.1.3 on 2024-12-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_kabacan_app', '0009_remove_tourist_number_of_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='number_of_visitors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
