# Generated by Django 5.1.3 on 2024-12-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_kabacan_app', '0010_alter_tourist_number_of_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
